//                  PLOT ACTONS
export const ENABLE_CHANNEL = 'ENABLE_CHANNELS';
export const DISABLE_CHANNEL = 'DISABLE_CHANNELS';
export const LOAD_CHANNELS = 'LOAD_CHANNELS';
export const PLOT_PLAY = 'PLOT_PLAY';
export const PLOT_PAUSE = 'PLOT_PAUSE';
export const PLOT_STOP = 'PLOT_STOP';
export const FETCH_DATA = 'FETCH_DATA';
export const SET_CHANNEL_SETTING = "SET_CHANNEL_SETTING";
//                   PARAMETERS ACTIONS
export const SAVE_PARAMETER =  'SEND_PARAMETER';
export const LOAD_PARAMETERS_DONE = 'LOAD_PARAMETERS_DONE';
//                   REGISTERS ACTIONS
export const LOAD_REGISTERS = 'LOAD_REGISTERS';
export const SEND_REGISTER = 'SEND_REGISTER';
//                   GENERAL SETTINGS ACTIONS
export const SET_SETTING = 'SET_PARAMETER_VALUE';
//                  TABS ACTIONS
export const LOAD_TABS = 'LOAD_TABS';
//                  MODAL ACTIONS
export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";
//                   SCRIPTS ACTIONS
export const ADD_SCRIPT = "ADD_SCRIPT";
export const REMOVE_SCRIPT = "REMOVE_SCRIPT";
export const LOAD_ALL_SCRIPTS = "LOAD_ALL_SCRIPTS";
export const SAVE_SCRIPTS = "SAVE_SCRIPTS";
export const SAVE_SCRIPT_WORKSPACE = "SAVE_SCRIPT_WORKSPACE";
//                  PERIPHERALS ACTIONS
export const LOAD_PERIPHERALS = 'LOAD_PERIPHERALS';
export const ADD_PERIPHERAL = 'ADD_PERIPHERAL';
export const REMOVE_PERIPHERAL = 'REMOVE_PERIPHERAL';
//                  APPLICATIONS ACTIONS
export const LOAD_APPLICATIONS = 'LOAD_APPLICATIONS';
export const ADD_APPLICATION = 'ADD_APPLICATION';
export const REMOVE_APPLICATION = 'REMOVE_APPLICATION';
