//                  PLOT ACTONS
export const SET_CHANNEL_STATUS = 'SET_CHANNEL_STATUS';
export const LOAD_CHANNELS = 'LOAD_CHANNELS';
export const PLOT_PLAY = 'PLOT_PLAY';
export const PLOT_PAUSE = 'PLOT_PAUSE';
export const PLOT_STOP = 'PLOT_STOP';
export const FETCH_DATA = 'FETCH_DATA';
export const SET_CHANNEL_SETTING = "SET_CHANNEL_SETTING";
export const INITIALIZE_CHANNELS = "INITIALIZE_CHANNELS";
//                   PARAMETERS ACTIONS
export const SAVE_PARAMETER =  'SEND_PARAMETER';
//                   REGISTERS ACTIONS
export const LOAD_REGISTERS = 'LOAD_REGISTERS';
export const SEND_REGISTER = 'SEND_REGISTER';
//                   GENERAL SETTINGS ACTIONS
export const SET_SETTING = 'SET_SETTING';
//                  VIEWS ACTIONS
export const LOAD_VIEWS = 'LOAD_VIEWS';
//                   SCRIPTS ACTIONS
export const ADD_SCRIPT = "ADD_SCRIPT";
export const REMOVE_SCRIPT = "REMOVE_SCRIPT";
export const LOAD_ALL_SCRIPTS = "LOAD_ALL_SCRIPTS";
export const EDIT_SCRIPT = "EDIT_SCRIPT";
export const SAVE_SCRIPTS = "SAVE_SCRIPTS";
export const SAVE_SCRIPT_WORKSPACE = "SAVE_SCRIPT_WORKSPACE";
//                  PERIPHERALS ACTIONS
export const LOAD_PERIPHERALS = 'LOAD_PERIPHERALS';
export const ADD_PERIPHERAL = 'ADD_PERIPHERAL';
export const EDIT_PERIPHERAL = 'EDIT_PERIPHERAL';
export const REMOVE_PERIPHERAL = 'REMOVE_PERIPHERAL';
//                  APPLICATIONS ACTIONS
export const LOAD_APPLICATIONS = 'LOAD_APPLICATIONS';
export const ADD_APPLICATION = 'ADD_APPLICATION';
export const EDIT_APPLICATION = 'EDIT_APPLICATION';
export const REMOVE_APPLICATION = 'REMOVE_APPLICATION';
//                  FCORE PROGRAMS
export const ADD_PROGRAM = "ADD_PROGRAM";
export const REMOVE_PROGRAM = "REMOVE_PROGRAM";
export const LOAD_ALL_PROGRAMS = "LOAD_ALL_PROGRAM";
export const EDIT_PROGRAM = "EDIT_PROGRAM";