//                   CHANNELS ACTIONS
export const ENABLE_CHANNEL = 'ENABLE_CHANNELS';
export const DISABLE_CHANNEL = 'DISABLE_CHANNELS';
export const LOAD_CHANNELS = 'LOAD_CHANNELS';
//                   PARAMETERS ACTIONS
export const SET_PARAMETER_VALUE = 'SET_PARAMETER_VALUE';
export const LOAD_PARAMETERS_DONE = 'LOAD_PARAMETERS_DONE';
//                   REGISTERS ACTIONS
export const LOAD_REGISTERS = 'LOAD_REGISTERS';
export const SEND_REGISTER = 'SEND_REGISTER';
export const SET_SINGLE_VALUE_REGISTER = 'SET_SINGLE_VALUE_REGISTER';
export const SET_TWO_VALUE_REGISTER = 'SET_TWO_VALUE_REGISTER';
//                   GENERAL SETTINGS ACTIONS
export const SET_SETTING = 'SET_PARAMETER_VALUE';
//                  TABS ACTIONS
export const LOAD_TABS = 'LOAD_TABS';