version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  client_setup:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
  server:
    docker:
      - image: circleci/python:3.8
    steps:
      - run: git clone git@github.com:filssavi/uscope_server.git
      - run: sudo pip install requirements.txt

workflows:
    build-and-test:
      jobs:
        - client_setup
        - server