// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!|Q]QPOOObQPO'#ChOjQPO'#C`OOQO'#Ci'#CiQ]QPOOOoQPO,59POOQO,58z,58zOOQO-E6g-E6gOtQPO1G.kO|QPO7+$XOOQO7+$V7+$VO!UQPO<<GmO!ZQPOAN=XO!cQPOG22vOOQOLD(bLD(b",
  stateData: "!k~O`OSPOSQOS~OUPO~OVTOa[X~OaUO~ObWO~OVXOYYO~ObZOaZq~OV[O~Ob]OaT!R~OV^O~Oa`~",
  goto: "m^PPPP_cPPccPccgTROSTQOSQSORVS",
  nodeNames: "⚠ LineComment BlockComment Program Instruction RegInstruction Opcode Register CselInstruction LoadInstruction Number ConvInstruction IndependentInstruction",
  maxTerm: 18,
  skippedNodes: [0,1,2],
  repeatNodeCount: 1,
  tokenData: "/a~RmXY!|YZ#qZ^!|pq!||}$h!P!Q$m!Q![)O#T#U)i#U#V*W#V#W+]#X#Y+o#Y#Z+{#]#^,R#`#a,_#a#b,k#b#c,z#c#d-Z#d#e-a#f#g-y#g#h.[#l#m/Z#y#z!|$f$g!|#BY#BZ!|$IS$I_!|$I|$JO!|$JT$JU!|$KV$KW!|&FU&FV!|~#RY`~X^!|pq!|#y#z!|$f$g!|#BY#BZ!|$IS$I_!|$I|$JO!|$JT$JU!|$KV$KW!|&FU&FV!|~#xYa~`~X^!|pq!|#y#z!|$f$g!|#BY#BZ!|$IS$I_!|$I|$JO!|$JT$JU!|$KV$KW!|&FU&FV!|~$mOb~~$pQz{$v!P!Q%}~$yTOz$vz{%Y{;'S$v;'S;=`%w<%lO$v~%]VOz$vz{%Y{!P$v!P!Q%r!Q;'S$v;'S;=`%w<%lO$v~%wOQ~~%zP;=`<%l$v~&SUP~OY%}Z#O%}#O#P&f#P;'S%};'S;=`(x<%lO%}~&kUP~OY%}Z#O%}#O#P&}#P;'S%};'S;=`(x<%lO%}~'SYP~OY%}Z#O%}#O#P&}#P#b%}#b#c%}#c#f%}#f#g'r#g;'S%};'S;=`(x<%lO%}~'wUP~OY%}Z#O%}#O#P(Z#P;'S%};'S;=`(x<%lO%}~(`WP~OY%}Z#O%}#O#P&}#P#b%}#b#c%}#c;'S%};'S;=`(x<%lO%}~({P;=`<%l%}~)TQY~!O!P)Z!Q![)O~)^P!Q![)a~)fPY~!Q![)a~)lR#U#V)u#W#X*Q#b#c*Q~)xP#g#h){~*QOU~~*TP#W#X){~*ZT#X#Y*j#Z#[*p#`#a*v#b#c*v#g#h*|~*mP#e#f){~*sP#h#i){~*yP#X#Y){~+PP#X#Y+S~+VQ#`#a){#h#i){~+`P#g#h+c~+fP#X#Y+i~+lP#`#a){~+rP#Y#Z+u~+xP#]#^){~,OP#h#i+u~,UP#h#i,X~,[P#Y#Z){~,bP#W#X,e~,hP#V#W){~,nQ#c#d,t#i#j+i~,wP#j#k){~,}P#c#d-Q~-TQ#d#e){#h#i){~-^P#f#g){~-dP#c#d-g~-jP#d#e-m~-pP#V#W-s~-vP#b#c*p~-|Q!Q![.S#X#Y,e~.XPV~!Q![.S~._R#T#U.h#h#i.w#i#j/T~.kP#h#i.n~.qQ#b#c){#d#e){~.zP#c#d.}~/QP#d#e){~/WP#U#V){~/^P#c#d-Z",
  tokenizers: [0],
  topRules: {"Program":[0,3]},
  tokenPrec: 70
})
