// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  LineComment = 1,
  BlockComment = 2,
  Program = 3,
  Instruction = 4,
  RegInstruction = 5,
  Opcode = 6,
  Register = 7,
  CselInstruction = 8,
  LoadInstruction = 9,
  Number = 10,
  ConvInstruction = 11,
  IndependentInstruction = 12
