// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "$nQ]QPOOOnQPO'#CaOsQPO'#CdOxQPO'#CfO}QPO'#CjOOQO'#Cp'#CpO!SQPO'#CmQ]QPOOO!XQPO,58{O!^QPO,59OO!cQPO,59QO!hQPO,59UOOQO,59X,59XOOQO-E6k-E6kO!mQPO1G.gO!rQPO1G.jO!wQPO1G.lO#PQPO1G.pO#UQPO7+$RO#ZQPO7+$UOOQO7+$W7+$WOOQO7+$[7+$[O#`QPO<<GmO#eQPO<<GpOOQOAN=XAN=XO#jQPOAN=[O#oQPOG22vOOQOLD(bLD(b",
  stateData: "#z~OPOSQOSROS~OUPOXQOZRO_SO`TO~OVWO~OVXO~OVYO~OVZO~Of[O~Oe^O~Oe_O~Oe`O~OeaO~OVbO~OVcO~O[dO]dO~OVeO~OefO~OegO~OVhO~OViO~OejO~OVkO~O[]fPf~",
  goto: "tePPPPPfPPfPfPPPfPPjPPpTTOVQVOR]VTUOV",
  nodeNames: "⚠ Space LineComment BlockComment Program RegInstruction RegOpcode Register CselInstruction CselOpcode LoadInstruction LoadOpcode FloatNumber IntegerNumber ConvInstruction ConvOpcode IndependentOpcode",
  maxTerm: 22,
  skippedNodes: [0,1,2,3],
  repeatNodeCount: 1,
  tokenData: "0_~RmXY!|YZ#qZ^!|pq!||}$h!P!Q$m!Q![)O#T#U)i#U#V*]#V#W+b#X#Y+y#Y#Z,V#]#^,c#`#a,o#a#b-Q#b#c-g#c#d-{#d#e.R#f#g.q#g#h/Y#l#m0X#y#z!|$f$g!|#BY#BZ!|$IS$I_!|$I|$JO!|$JT$JU!|$KV$KW!|&FU&FV!|~#RYP~X^!|pq!|#y#z!|$f$g!|#BY#BZ!|$IS$I_!|$I|$JO!|$JT$JU!|$KV$KW!|&FU&FV!|~#xYf~P~X^!|pq!|#y#z!|$f$g!|#BY#BZ!|$IS$I_!|$I|$JO!|$JT$JU!|$KV$KW!|&FU&FV!|~$mOe~~$pQz{$v!P!Q%}~$yTOz$vz{%Y{;'S$v;'S;=`%w<%lO$v~%]VOz$vz{%Y{!P$v!P!Q%r!Q;'S$v;'S;=`%w<%lO$v~%wOR~~%zP;=`<%l$v~&SUQ~OY%}Z#O%}#O#P&f#P;'S%};'S;=`(x<%lO%}~&kUQ~OY%}Z#O%}#O#P&}#P;'S%};'S;=`(x<%lO%}~'SYQ~OY%}Z#O%}#O#P&}#P#b%}#b#c%}#c#f%}#f#g'r#g;'S%};'S;=`(x<%lO%}~'wUQ~OY%}Z#O%}#O#P(Z#P;'S%};'S;=`(x<%lO%}~(`WQ~OY%}Z#O%}#O#P&}#P#b%}#b#c%}#c;'S%};'S;=`(x<%lO%}~({P;=`<%l%}~)TQ]~!O!P)Z!Q![)O~)^P!Q![)a~)fP[~!Q![)a~)lR#U#V)u#W#X*Q#b#c*Q~)xP#g#h){~*QO_~~*TP#W#X*W~*]OU~~*`T#X#Y*o#Z#[*u#`#a*{#b#c*{#g#h+R~*rP#e#f*W~*xP#h#i*W~+OP#X#Y*W~+UP#X#Y+X~+[Q#`#a*W#h#i*W~+eP#g#h+h~+kP#X#Y+n~+qP#`#a+t~+yOX~~+|P#Y#Z,P~,SP#]#^*W~,YP#h#i,]~,`P#]#^){~,fP#h#i,i~,lP#Y#Z){~,rP#W#X,u~,xP#V#W,{~-QOZ~~-TQ#c#d-Z#i#j-a~-^P#j#k){~-dP#`#a*W~-jP#c#d-m~-pQ#d#e-v#h#i){~-{O`~~.OP#f#g*W~.UP#c#d.X~.[P#d#e._~.bP#V#W.e~.hP#b#c.k~.nP#h#i){~.tQ!Q![.z#X#Y/S~/PPV~!Q![.z~/VP#V#W){~/]R#T#U/f#h#i/u#i#j0R~/iP#h#i/l~/oQ#b#c*W#d#e*W~/xP#c#d/{~0OP#d#e-v~0UP#U#V*W~0[P#c#d-{",
  tokenizers: [0],
  topRules: {"Program":[0,4]},
  tokenPrec: 128
})
