// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Space = 1,
  LineComment = 2,
  BlockComment = 3,
  Program = 4,
  RegInstruction = 5,
  RegOpcode = 6,
  Register = 7,
  CselInstruction = 8,
  CselOpcode = 9,
  LoadInstruction = 10,
  LoadOpcode = 11,
  FloatNumber = 12,
  IntegerNumber = 13,
  ConvInstruction = 14,
  ConvOpcode = 15,
  IndependentOpcode = 16
